name: Publish to WinGet

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  winget:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    steps:
      - name: Submit to WinGet Community Repository
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Orwell-coder.goshare
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
